export const nationalityOptions = [
  { value: "Afghan", label: "Afghan", flag: "🇦🇫" },
  { value: "Albanian", label: "Albanian", flag: "🇦🇱" },
  { value: "Algerian", label: "Algerian", flag: "🇩🇿" },
  { value: "American", label: "American", flag: "🇺🇸" },
  { value: "Andorran", label: "Andorran", flag: "🇦🇩" },
  { value: "Angolan", label: "Angolan", flag: "🇦🇴" },
  { value: "Antiguan and Barbudan", label: "Antiguan and Barbudan", flag: "🇦🇬" },
  { value: "Argentine", label: "Argentine", flag: "🇦🇷" },
  { value: "Armenian", label: "Armenian", flag: "🇦🇲" },
  { value: "Australian", label: "Australian", flag: "🇦🇺" },
  { value: "Austrian", label: "Austrian", flag: "🇦🇹" },
  { value: "Azerbaijani", label: "Azerbaijani", flag: "🇦🇿" },
  { value: "Bahamian", label: "Bahamian", flag: "🇧🇸" },
  { value: "Bahraini", label: "Bahraini", flag: "🇧🇭" },
  { value: "Bangladeshi", label: "Bangladeshi", flag: "🇧🇩" },
  { value: "Barbadian", label: "Barbadian", flag: "🇧🇧" },
  { value: "Belarusian", label: "Belarusian", flag: "🇧🇾" },
  { value: "Belgian", label: "Belgian", flag: "🇧🇪" },
  { value: "Belizean", label: "Belizean", flag: "🇧🇿" },
  { value: "Beninese", label: "Beninese", flag: "🇧🇯" },
  { value: "Bhutanese", label: "Bhutanese", flag: "🇧🇹" },
  { value: "Bolivian", label: "Bolivian", flag: "🇧🇴" },
  { value: "Bosnian", label: "Bosnian", flag: "🇧🇦" },
  { value: "Botswanan", label: "Botswanan", flag: "🇧🇼" },
  { value: "Brazilian", label: "Brazilian", flag: "🇧🇷" },
  { value: "Bruneian", label: "Bruneian", flag: "🇧🇳" },
  { value: "British", label: "British", flag: "🇬🇧" },
  { value: "Bulgarian", label: "Bulgarian", flag: "🇧🇬" },
  { value: "Burkinabe", label: "Burkinabe", flag: "🇧🇫" },
  { value: "Burundian", label: "Burundian", flag: "🇧🇮" },
  { value: "Cambodian", label: "Cambodian", flag: "🇰🇭" },
  { value: "Cameroonian", label: "Cameroonian", flag: "🇨🇲" },
  { value: "Canadian", label: "Canadian", flag: "🇨🇦" },
  { value: "Cape Verdean", label: "Cape Verdean", flag: "🇨🇻" },
  { value: "Central African", label: "Central African", flag: "🇨🇫" },
  { value: "Chadian", label: "Chadian", flag: "🇹🇩" },
  { value: "Chilean", label: "Chilean", flag: "🇨🇱" },
  { value: "Chinese", label: "Chinese", flag: "🇨🇳" },
  { value: "Colombian", label: "Colombian", flag: "🇨🇴" },
  { value: "Comorian", label: "Comorian", flag: "🇰🇲" },
  { value: "Congolese", label: "Congolese", flag: "🇨🇬" },
  { value: "Costa Rican", label: "Costa Rican", flag: "🇨🇷" },
  { value: "Croatian", label: "Croatian", flag: "🇭🇷" },
  { value: "Cuban", label: "Cuban", flag: "🇨🇺" },
  { value: "Cypriot", label: "Cypriot", flag: "🇨🇾" },
  { value: "Czech", label: "Czech", flag: "🇨🇿" },
  { value: "Danish", label: "Danish", flag: "🇩🇰" },
  { value: "Djiboutian", label: "Djiboutian", flag: "🇩🇯" },
  { value: "Dominican", label: "Dominican", flag: "🇩🇲" },
  { value: "Dominican Republic", label: "Dominican Republic", flag: "🇩🇴" },
  { value: "Dutch", label: "Dutch", flag: "🇳🇱" },
  { value: "Ecuadorian", label: "Ecuadorian", flag: "🇪🇨" },
  { value: "Egyptian", label: "Egyptian", flag: "🇪🇬" },
  { value: "Emirati", label: "Emirati", flag: "🇦🇪" },
  { value: "Equatorial Guinean", label: "Equatorial Guinean", flag: "🇬🇶" },
  { value: "Eritrean", label: "Eritrean", flag: "🇪🇷" },
  { value: "Estonian", label: "Estonian", flag: "🇪🇪" },
  { value: "Eswatini", label: "Eswatini", flag: "🇸🇿" },
  { value: "Ethiopian", label: "Ethiopian", flag: "🇪🇹" },
  { value: "Fijian", label: "Fijian", flag: "🇫🇯" },
  { value: "Filipino", label: "Filipino", flag: "🇵🇭" },
  { value: "Finnish", label: "Finnish", flag: "🇫🇮" },
  { value: "French", label: "French", flag: "🇫🇷" },
  { value: "Gabonese", label: "Gabonese", flag: "🇬🇦" },
  { value: "Gambian", label: "Gambian", flag: "🇬🇲" },
  { value: "Georgian", label: "Georgian", flag: "🇬🇪" },
  { value: "German", label: "German", flag: "🇩🇪" },
  { value: "Ghanaian", label: "Ghanaian", flag: "🇬🇭" },
  { value: "Greek", label: "Greek", flag: "🇬🇷" },
  { value: "Grenadian", label: "Grenadian", flag: "🇬🇩" },
  { value: "Guatemalan", label: "Guatemalan", flag: "🇬🇹" },
  { value: "Guinean", label: "Guinean", flag: "🇬🇳" },
  { value: "Guinea-Bissauan", label: "Guinea-Bissauan", flag: "🇬🇼" },
  { value: "Guyanese", label: "Guyanese", flag: "🇬🇾" },
  { value: "Haitian", label: "Haitian", flag: "🇭🇹" },
  { value: "Honduran", label: "Honduran", flag: "🇭🇳" },
  { value: "Hungarian", label: "Hungarian", flag: "🇭🇺" },
  { value: "Icelandic", label: "Icelandic", flag: "🇮🇸" },
  { value: "Indian", label: "Indian", flag: "🇮🇳" },
  { value: "Indonesian", label: "Indonesian", flag: "🇮🇩" },
  { value: "Iranian", label: "Iranian", flag: "🇮🇷" },
  { value: "Iraqi", label: "Iraqi", flag: "🇮🇶" },
  { value: "Irish", label: "Irish", flag: "🇮🇪" },
  { value: "Italian", label: "Italian", flag: "🇮🇹" },
  { value: "Ivorian", label: "Ivorian", flag: "🇨🇮" },
  { value: "Jamaican", label: "Jamaican", flag: "🇯🇲" },
  { value: "Japanese", label: "Japanese", flag: "🇯🇵" },
  { value: "Jordanian", label: "Jordanian", flag: "🇯🇴" },
  { value: "Kazakh", label: "Kazakh", flag: "🇰🇿" },
  { value: "Kenyan", label: "Kenyan", flag: "🇰🇪" },
  { value: "Kiribati", label: "Kiribati", flag: "🇰🇮" },
  { value: "Kuwaiti", label: "Kuwaiti", flag: "🇰🇼" },
  { value: "Kosovan", label: "Kosovan", flag: "🇽🇰" },
  { value: "Kyrgyz", label: "Kyrgyz", flag: "🇰🇬" },
  { value: "Laotian", label: "Laotian", flag: "🇱🇦" },
  { value: "Latvian", label: "Latvian", flag: "🇱🇻" },
  { value: "Lebanese", label: "Lebanese", flag: "🇱🇧" },
  { value: "Liberian", label: "Liberian", flag: "🇱🇷" },
  { value: "Libyan", label: "Libyan", flag: "🇱🇾" },
  { value: "Liechtensteiner", label: "Liechtensteiner", flag: "🇱🇮" },
  { value: "Lithuanian", label: "Lithuanian", flag: "🇱🇹" },
  { value: "Luxembourger", label: "Luxembourger", flag: "🇱🇺" },
  { value: "Malagasy", label: "Malagasy", flag: "🇲🇬" },
  { value: "Malawian", label: "Malawian", flag: "🇲🇼" },
  { value: "Malaysian", label: "Malaysian", flag: "🇲🇾" },
  { value: "Maldivian", label: "Maldivian", flag: "🇲🇻" },
  { value: "Malian", label: "Malian", flag: "🇲🇱" },
  { value: "Maltese", label: "Maltese", flag: "🇲🇹" },
  { value: "Marshallese", label: "Marshallese", flag: "🇲🇭" },
  { value: "Mauritanian", label: "Mauritanian", flag: "🇲🇷" },
  { value: "Mauritian", label: "Mauritian", flag: "🇲🇺" },
  { value: "Mexican", label: "Mexican", flag: "🇲🇽" },
  { value: "Micronesian", label: "Micronesian", flag: "🇫🇲" },
  { value: "Moldovan", label: "Moldovan", flag: "🇲🇩" },
  { value: "Monacan", label: "Monacan", flag: "🇲🇨" },
  { value: "Mongolian", label: "Mongolian", flag: "🇲🇳" },
  { value: "Montenegrin", label: "Montenegrin", flag: "🇲🇪" },
  { value: "Moroccan", label: "Moroccan", flag: "🇲🇦" },
  { value: "Mozambican", label: "Mozambican", flag: "🇲🇿" },
  { value: "Myanmar", label: "Myanmar", flag: "🇲🇲" },
  { value: "Namibian", label: "Namibian", flag: "🇳🇦" },
  { value: "Nauruan", label: "Nauruan", flag: "🇳🇷" },
  { value: "Nepalese", label: "Nepalese", flag: "🇳🇵" },
  { value: "New Zealander", label: "New Zealander", flag: "🇳🇿" },
  { value: "Nicaraguan", label: "Nicaraguan", flag: "🇳🇮" },
  { value: "Nigerien", label: "Nigerien", flag: "🇳🇪" },
  { value: "Nigerian", label: "Nigerian", flag: "🇳🇬" },
  { value: "North Korean", label: "North Korean", flag: "🇰🇵" },
  { value: "North Macedonian", label: "North Macedonian", flag: "🇲🇰" },
  { value: "Norwegian", label: "Norwegian", flag: "🇳🇴" },
  { value: "Omani", label: "Omani", flag: "🇴🇲" },
  { value: "Pakistani", label: "Pakistani", flag: "🇵🇰" },
  { value: "Palauan", label: "Palauan", flag: "🇵🇼" },
  { value: "Panamanian", label: "Panamanian", flag: "🇵🇦" },
  { value: "Palestinian", label: "Palestinian", flag: "🇵🇸" },
  { value: "Papua New Guinean", label: "Papua New Guinean", flag: "🇵🇬" },
  { value: "Paraguayan", label: "Paraguayan", flag: "🇵🇾" },
  { value: "Peruvian", label: "Peruvian", flag: "🇵🇪" },
  { value: "Polish", label: "Polish", flag: "🇵🇱" },
  { value: "Portuguese", label: "Portuguese", flag: "🇵🇹" },
  { value: "Qatari", label: "Qatari", flag: "🇶🇦" },
  { value: "Romanian", label: "Romanian", flag: "🇷🇴" },
  { value: "Russian", label: "Russian", flag: "🇷🇺" },
  { value: "Rwandan", label: "Rwandan", flag: "🇷🇼" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { value: "Saint Lucian", label: "Saint Lucian", flag: "🇱🇨" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { value: "Salvadoran", label: "Salvadoran", flag: "🇸🇻" },
  { value: "Samoan", label: "Samoan", flag: "🇼🇸" },
  { value: "San Marinese", label: "San Marinese", flag: "🇸🇲" },
  { value: "Sao Tomean", label: "Sao Tomean", flag: "🇸🇹" },
  { value: "Saudi", label: "Saudi", flag: "🇸🇦" },
  { value: "Senegalese", label: "Senegalese", flag: "🇸🇳" },
  { value: "Serbian", label: "Serbian", flag: "🇷🇸" },
  { value: "Seychellois", label: "Seychellois", flag: "🇸🇨" },
  { value: "Sierra Leonean", label: "Sierra Leonean", flag: "🇸🇱" },
  { value: "Singaporean", label: "Singaporean", flag: "🇸🇬" },
  { value: "Slovak", label: "Slovak", flag: "🇸🇰" },
  { value: "Slovenian", label: "Slovenian", flag: "🇸🇮" },
  { value: "Solomon Islander", label: "Solomon Islander", flag: "🇸🇧" },
  { value: "Somali", label: "Somali", flag: "🇸🇴" },
  { value: "South African", label: "South African", flag: "🇿🇦" },
  { value: "South Korean", label: "South Korean", flag: "🇰🇷" },
  { value: "South Sudanese", label: "South Sudanese", flag: "🇸🇸" },
  { value: "Spanish", label: "Spanish", flag: "🇪🇸" },
  { value: "Sri Lankan", label: "Sri Lankan", flag: "🇱🇰" },
  { value: "Sudanese", label: "Sudanese", flag: "🇸🇩" },
  { value: "Surinamese", label: "Surinamese", flag: "🇸🇷" },
  { value: "Swedish", label: "Swedish", flag: "🇸🇪" },
  { value: "Swiss", label: "Swiss", flag: "🇨🇭" },
  { value: "Syrian", label: "Syrian", flag: "🇸🇾" },
  { value: "Taiwanese", label: "Taiwanese", flag: "🇹🇼" },
  { value: "Tajik", label: "Tajik", flag: "🇹🇯" },
  { value: "Tanzanian", label: "Tanzanian", flag: "🇹🇿" },
  { value: "Thai", label: "Thai", flag: "🇹🇭" },
  { value: "Timorese", label: "Timorese", flag: "🇹🇱" },
  { value: "Togolese", label: "Togolese", flag: "🇹🇬" },
  { value: "Tongan", label: "Tongan", flag: "🇹🇴" },
  { value: "Trinidadian and Tobagonian", label: "Trinidadian and Tobagonian", flag: "🇹🇹" },
  { value: "Tunisian", label: "Tunisian", flag: "🇹🇳" },
  { value: "Turkish", label: "Turkish", flag: "🇹🇷" },
  { value: "Turkmen", label: "Turkmen", flag: "🇹🇲" },
  { value: "Tuvaluan", label: "Tuvaluan", flag: "🇹🇻" },
  { value: "Ugandan", label: "Ugandan", flag: "🇺🇬" },
  { value: "Ukrainian", label: "Ukrainian", flag: "🇺🇦" },
  { value: "Uruguayan", label: "Uruguayan", flag: "🇺🇾" },
  { value: "Uzbek", label: "Uzbek", flag: "🇺🇿" },
  { value: "Vanuatuan", label: "Vanuatuan", flag: "🇻🇺" },
  { value: "Vatican", label: "Vatican", flag: "🇻🇦" },
  { value: "Venezuelan", label: "Venezuelan", flag: "🇻🇪" },
  { value: "Vietnamese", label: "Vietnamese", flag: "🇻🇳" },
  { value: "Yemeni", label: "Yemeni", flag: "🇾🇪" },
  { value: "Zambian", label: "Zambian", flag: "🇿🇲" },
  { value: "Zimbabwean", label: "Zimbabwean", flag: "🇿🇼" },
];
